### ISSUE TITLE
ASN.1 compiler failed - [Errno2] No such file or directory: 'dataview-uniq.asn'

### ISSUE THREAD

**Issue by nuaaysh** [esa/opengeode#68] opened 2020-07-03 01:42 UTC
Hello, 
      I try to check my SDL model, but it returns this kind of error: ASN.1 compiler failed - [Errno2] No such file or directory: 'dataview-uniq.asn'. 
      But the .asn file exists and is at the same folder with the .pr file. The screenshot also shows the opengeode has read the .asn file.
      ![sdl.png](https://i.loli.net/2020/07/03/vyjhK62IMrQY3LV.png)
      I follow the readme to install the asn compiler. Could you please give me some suggestions?
      In fact, when I try the TASTE tool, the SDL model is right.    
      Some information is listed as follow:
```
..:~$ mono /opt/asn1scc/asn1.exe -v
asn1scc version 4.2.1.3f
..:~$ echo $PATH
..:/opt/asn1scc:..
...:~$ opengeode -v
3.0.8
```
Best wishes,

**Comment by maxime-esa** [comment] 2020-07-03 06:13
I don't understand. Your screenshot shows the ASN.1 types, meaning that the model was loaded.
Can you show the complete error log on the bottom of the screen ?

**Comment by nuaaysh** [comment] 2020-07-03 06:30
I check the same model and show the error information from the terminal:

```
...:~$ opengeode
[INFO] Model backup enabled - auto-saving every 2 minutes
[ERROR] ASN.1 compiler failed - [Errno 2] No such file or directory: 'dataview-uniq.asn'
[ERROR] Type DEVICE_PowerOn_Command not found in ASN.1 model
[ERROR] File not found: dataview-uniq.asn
[ERROR] File not found: dataview-uniq.asn
[ERROR] File not found: dataview-uniq.asn
[ERROR] Type DEVICE_PowerOn_Command not found in ASN.1 model(line 33)
[ERROR] Type Trigger not found in ASN.1 model
[ERROR] Type Trigger not found in ASN.1 model - "t Trigger"
[ERROR] Type Trigger not found in ASN.1 model(line 48)
[ERROR] Type Trigger not found in ASN.1 model - "trigger Trigger"
[ERROR] Type DEVICE_PowerOn_Command not found in ASN.1 model - "dpc DEVICE_PowerOn_Command"
[ERROR] Wrong number of parameters or type mismatch
[ERROR] In call to data_parser: Type of parameter 1 is incorrect (UnknownType) - Cannot resolve type of "dpc" - "data_parser(dpc)"
[ERROR] In "trigger:=data_parser(dpc)": Type mismatch (UnknownType vs UnknownType - Cannot resolve type of "data_parser(dpc)")
[ERROR] In call to trigger_start: Type of parameter 1 is incorrect (UnknownType) - Cannot resolve type of "trigger" - trigger_start(trigger)
[ERROR] No return value expected in procedure data_parser
```

**Comment by maxime-esa** [comment] 2020-07-03 06:53
Can you run opengeode with the `-g` flag and report the output (just the exact call to the ASN.1 compiler, not all the errors afterwards)?

**Comment by nuaaysh** [comment] 2020-07-03 07:05
OK, Here is the report:

```
...:~$ opengeode -g
[DEBUG] Starting OpenGEODE version 3.0.8
[DEBUG] Running the GUI
[INFO] Model backup enabled - auto-saving every 2 minutes
[DEBUG] [QGraphicsView] ResizeEvent
[DEBUG] [QGraphicsView] ResizeEvent
[DEBUG] Parsed 0 process(es),  0 use statatement(s),  and 0 systems
[DEBUG] No statechart to render (no process or process type)
[DEBUG] Traceback (most recent call last):
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/opengeode.py", line 2675, in upd_statechart
    Statechart.render_statechart(self.statechart_scene,
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/Statechart.py", line 449, in render_statechart
    raise TypeError ("Statechart.py: 'render_statechart'"
TypeError: Statechart.py: 'render_statechart' called with no graph tree

[DEBUG] Statechart error: Statechart.py: 'render_statechart' called with no graph tree
[DEBUG] [QGraphicsView] ResizeEvent
[DEBUG] [QGraphicsView] ResizeEvent
[DEBUG] [QGraphicsView] ResizeEvent
[DEBUG] [QGraphicsView] ResizeEvent
[DEBUG] [QGraphicsView] ResizeEvent
[DEBUG] [QGraphicsView] ResizeEvent
[DEBUG] [QGraphicsView] ResizeEvent
[DEBUG] [QGraphicsView] ResizeEvent
[DEBUG] Parsed 0 process(es),  0 use statatement(s),  and 1 systems
[DEBUG] /media/shyuan/Elements/xiaoxin/SDL/DP
[DEBUG] /media/shyuan/Elements/xiaoxin/SDL/DP
[DEBUG] ['/opt/asn1scc/asn1.exe', '-customStgAstVersion', '4', '-customStg', '/opt/asn1scc/python.stg::/tmp/tmp4q9yt45d/21279baa8438f4b740b96aab7592d1dc.py', '-renamePolicy', '0', '-customIcdUper', '/tmp/tmp4q9yt45d/pretty_print_asn1.stg::/tmp/tmp4q9yt45d/21279baa8438f4b740b96aab7592d1dc.html', 'dataview-uniq.asn']
[DEBUG] ['/opt/asn1scc/asn1.exe', '-customStgAstVersion', '4', '-customStg', '/opt/asn1scc/python.stg::/tmp/tmp4q9yt45d/21279baa8438f4b740b96aab7592d1dc.py', '-renamePolicy', '0', '-customIcdUper', '/tmp/tmp4q9yt45d/pretty_print_asn1.stg::/tmp/tmp4q9yt45d/21279baa8438f4b740b96aab7592d1dc.html', 'dataview-uniq.asn']
[DEBUG] /usr/bin/mono /opt/asn1scc/asn1.exe -customStgAstVersion 4 -customStg /opt/asn1scc/python.stg::/tmp/tmp4q9yt45d/21279baa8438f4b740b96aab7592d1dc.py -renamePolicy 0 -customIcdUper /tmp/tmp4q9yt45d/pretty_print_asn1.stg::/tmp/tmp4q9yt45d/21279baa8438f4b740b96aab7592d1dc.html dataview-uniq.asn
[DEBUG] /usr/bin/mono /opt/asn1scc/asn1.exe -customStgAstVersion 4 -customStg /opt/asn1scc/python.stg::/tmp/tmp4q9yt45d/21279baa8438f4b740b96aab7592d1dc.py -renamePolicy 0 -customIcdUper /tmp/tmp4q9yt45d/pretty_print_asn1.stg::/tmp/tmp4q9yt45d/21279baa8438f4b740b96aab7592d1dc.html dataview-uniq.asn
[DEBUG] Parsing complete. Summary, found 0 warnings and 0 errors
[DEBUG] resize item
[DEBUG] Recursive scene: DP
[DEBUG] Created scene: DP
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] Recursive scene: -
[DEBUG] Subscene "-" ignored
[DEBUG] Recursive scene: data_parse
[DEBUG] Subscene "data_parse" ignored
[DEBUG] Recursive scene: data_parser
[DEBUG] Created scene: data_parser
[DEBUG] resize item
[DEBUG] Recursive scene: trigger_start
[DEBUG] Created scene: trigger_start
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] resize item
[DEBUG] Parsing string: /* CIF TEXT (295, 241), (538, 281) */
-- Text area for declarations and comments
use dv comment 'dataview-uniq.asn';
signal DPC(DEVICE_PowerOn_Command);
signal DCC; 
signal DSM;
/* CIF ENDTEXT */ with elem text_area
[DEBUG] Traceback (most recent call last):
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/Asn1scc.py", line 98, in parse_asn1
    filehash.update(open(each).read().encode('utf-8'))
FileNotFoundError: [Errno 2] No such file or directory: 'dataview-uniq.asn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 200, in set_global_DV
    DV = parse_asn1(tuple(asn1_filenames),
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/Asn1scc.py", line 104, in parse_asn1
    raise TypeError (str(err))
TypeError: [Errno 2] No such file or directory: 'dataview-uniq.asn'

[DEBUG] Parsing string: /* CIF PROCESS (297, 111), (147, 75) */
process DP;
endprocess DP; with elem process_definition
[DEBUG] Discarding process DP 'NoneType' object has no attribute 'blocks'
[DEBUG] Parsing string: /* CIF NEXTSTATE (356, 459), (70, 40) */
NEXTSTATE -; with elem terminator_statement
[DEBUG] Parsing string: /* CIF output (347, 399), (88, 40) */
output DSM; with elem output
[DEBUG] [outputbody] call check_and_fix_op_params : DSMOperator/output/procedure not found: dsm
[DEBUG] Traceback (most recent call last):
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 4183, in outputbody
    check_call(body.get('outputName', '').lower(),
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 718, in check_call
    sign = signature(name, context)
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 584, in signature
    raise AttributeError('Operator/output/procedure not found: ' + name)
AttributeError: Operator/output/procedure not found: dsm

[DEBUG] Parsing string: /* CIF output (353, 339), (75, 40) */
output DCC; with elem output
[DEBUG] [outputbody] call check_and_fix_op_params : DCCOperator/output/procedure not found: dcc
[DEBUG] Traceback (most recent call last):
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 4183, in outputbody
    check_call(body.get('outputName', '').lower(),
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 718, in check_call
    sign = signature(name, context)
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 584, in signature
    raise AttributeError('Operator/output/procedure not found: ' + name)
AttributeError: Operator/output/procedure not found: dcc

[DEBUG] Parsing string: /* CIF PROCEDURECALL (250, 279), (281, 40) */
call trigger_start(trigger); with elem procedure_call
[DEBUG] [outputbody] call check_and_fix_op_params : trigger_start(trigger)Operator/output/procedure not found: trigger_start
[DEBUG] Traceback (most recent call last):
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 4183, in outputbody
    check_call(body.get('outputName', '').lower(),
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 718, in check_call
    sign = signature(name, context)
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 584, in signature
    raise AttributeError('Operator/output/procedure not found: ' + name)
AttributeError: Operator/output/procedure not found: trigger_start

[DEBUG] Parsing string: /* CIF task (222, 219), (337, 40) */
task trigger:=data_parser(dpc); with elem task
[DEBUG] right: data_parser(dpc)
[DEBUG] left: trigger
[DEBUG] Traceback (most recent call last):
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 4874, in assign
    warnings.extend(fix_expression_types(expr, context))
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 1346, in fix_expression_types
    raise TypeError('Cannot resolve type of "{}"'
TypeError: Cannot resolve type of "data_parser(dpc)"

[DEBUG] Parsing string: /* CIF input (323, 159), (136, 40) */
input DPC(dpc); with elem input_part
[DEBUG] Parsing string: /* CIF NEXTSTATE (312, 94), (158, 40) */
NEXTSTATE data_parse; with elem terminator_statement
[DEBUG] Parsing string: /* CIF START (357, 39), (70, 35) */
START; with elem start
[DEBUG] Parsing string: /* CIF procedure (67, 222), (170, 40) */
procedure data_parser;
endprocedure; with elem procedure
[DEBUG] Parsing string: /* CIF procedure (52, 300), (179, 40) */
procedure trigger_start;
endprocedure; with elem procedure
[DEBUG] Parsing string: /* CIF TEXT (0, 50), (529, 140) */
-- Text area for declarations and comments

dcl trigger Trigger;
dcl dpc DEVICE_PowerOn_Command;
/* CIF ENDTEXT */ with elem text_area
[DEBUG] Parsing string: /* CIF return (406, 102), (35, 35) */
return t; with elem terminator_statement
[DEBUG] Parsing string: /* CIF START (389, 47), (70, 35) */
START; with elem start
[DEBUG] Parsing string: /* CIF TEXT (39, 41), (529, 200) */
-- Text area for declarations and comments

fpar in dpc DEVICE_PowerOn_Command;
returns Trigger;

DCL t Trigger;
/* CIF ENDTEXT */ with elem text_area
[DEBUG] Parsing string: /* CIF return (417, 106), (35, 35) */
return ; with elem terminator_statement
[DEBUG] Parsing string: /* CIF START (400, 51), (70, 35) */
START; with elem start
[DEBUG] Parsing string: /* CIF TEXT (40, 50), (529, 104) */
-- Text area for declarations and comments

fpar in trigger Trigger;
/* CIF ENDTEXT */ with elem text_area
[DEBUG] Parsed 0 process(es),  0 use statatement(s),  and 1 systems
[DEBUG] Traceback (most recent call last):
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/Asn1scc.py", line 98, in parse_asn1
    filehash.update(open(each).read().encode('utf-8'))
FileNotFoundError: [Errno 2] No such file or directory: 'dataview-uniq.asn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 200, in set_global_DV
    DV = parse_asn1(tuple(asn1_filenames),
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/Asn1scc.py", line 104, in parse_asn1
    raise TypeError (str(err))
TypeError: [Errno 2] No such file or directory: 'dataview-uniq.asn'

[DEBUG] right: dpc
[DEBUG] left: 
[DEBUG] right: data_parser(dpc)
[DEBUG] left: trigger
[DEBUG] Traceback (most recent call last):
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 4874, in assign
    warnings.extend(fix_expression_types(expr, context))
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 1346, in fix_expression_types
    raise TypeError('Cannot resolve type of "{}"'
TypeError: Cannot resolve type of "data_parser(dpc)"

[DEBUG] right: trigger
[DEBUG] left: 
[DEBUG] [outputbody] call check_and_fix_op_params : trigger_start(trigger)In call to trigger_start: Type of parameter 1 is incorrect (UnknownType) - Cannot resolve type of "trigger"
[DEBUG] Traceback (most recent call last):
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 737, in check_call
    warnings.extend(fix_expression_types(expr, context))
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 1346, in fix_expression_types
    raise TypeError('Cannot resolve type of "{}"'
TypeError: Cannot resolve type of "trigger"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 4183, in outputbody
    check_call(body.get('outputName', '').lower(),
  File "/home/shyuan/.local/lib/python3.8/site-packages/opengeode/ogParser.py", line 742, in check_call
    raise TypeError('In call to {}: Type of parameter {} is incorrect'
TypeError: In call to trigger_start: Type of parameter 1 is incorrect (UnknownType) - Cannot resolve type of "trigger"

[ERROR] ASN.1 compiler failed - [Errno 2] No such file or directory: 'dataview-uniq.asn'
[ERROR] Type DEVICE_PowerOn_Command not found in ASN.1 model
[ERROR] File not found: dataview-uniq.asn
[ERROR] File not found: dataview-uniq.asn
[ERROR] File not found: dataview-uniq.asn
[ERROR] Type DEVICE_PowerOn_Command not found in ASN.1 model(line 33)
[ERROR] Type Trigger not found in ASN.1 model
[ERROR] Type Trigger not found in ASN.1 model - "t Trigger"
[ERROR] Type Trigger not found in ASN.1 model(line 48)
[ERROR] Type Trigger not found in ASN.1 model - "trigger Trigger"
[ERROR] Type DEVICE_PowerOn_Command not found in ASN.1 model - "dpc DEVICE_PowerOn_Command"
[ERROR] Wrong number of parameters or type mismatch
[ERROR] In call to data_parser: Type of parameter 1 is incorrect (UnknownType) - Cannot resolve type of "dpc" - "data_parser(dpc)"
[ERROR] In "trigger:=data_parser(dpc)": Type mismatch (UnknownType vs UnknownType - Cannot resolve type of "data_parser(dpc)")
[ERROR] In call to trigger_start: Type of parameter 1 is incorrect (UnknownType) - Cannot resolve type of "trigger" - trigger_start(trigger)
[ERROR] No return value expected in procedure data_parser
[DEBUG] set_asn1_view: No ASN.1 file specified
```

**Comment by maxime-esa** [comment] 2020-07-03 08:06
I am unable to reproduce. It's not the call to asn1scc that fails, it's the Python call to "open("dataview-uniq.asn")" that says FileNotFound. If the ASN.1 file is in the same folder as the SDL model (.pr) I do not see how this can fail.

Can you send me a tarball with the files for me to check what is going wrong?

Thanks

**Comment by nuaaysh** [comment] 2020-07-03 08:42
Hi,
I have sent an email to you (Maxime.Perrotin@esa.int). The attachment includes my SDL project (.pr and .asn files)
Best wishes,

**Comment by maxime-esa** [comment] 2020-07-03 20:34
Thanks. This should be fixed now. The tool was loosing track of the working folder when the model was loaded from a different directory.

**Comment by nuaaysh** [comment] 2020-07-04 11:40
Many Thanks! I test it just now, it works! Thanks for the good SDL tool provided by you.

**Closed** 2020-07-04 11:40 UTC
